<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Job;
use Carbon\Carbon;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // ⚠️ TEMPORARILY DISABLED - Uncomment below to enable job data seeding
        /* $jobs = [
            [
                'company_id' => 1,
                'category_id' => 1,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 1,
                'job_type_id' => 1,
                'title' => 'Senior PHP Developer',
                'slug' => 'senior-php-developer',
                'description' => 'We are looking for an experienced PHP developer to join our team. You will be responsible for developing and maintaining web applications using modern PHP frameworks.',
                'responsibilities' => 'Develop web applications, maintain existing code, collaborate with team members, write clean and efficient code.',
                'requirements' => 'Bachelor\'s degree in Computer Science, 3+ years PHP experience, knowledge of Laravel framework.',
                'min_experience_months' => 36,
                'salary_min' => 80000,
                'salary_max' => 120000,
                'currency' => 'PKR',
                'vacancies' => 2,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(5),
                'last_apply_date' => Carbon::now()->addDays(30),
                'is_active' => 1
            ],
            [
                'company_id' => 2,
                'category_id' => 5,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 2,
                'job_type_id' => 1,
                'title' => 'Digital Marketing Manager',
                'slug' => 'digital-marketing-manager',
                'description' => 'Join our dynamic marketing team to create and execute digital marketing campaigns for our clients.',
                'responsibilities' => 'Plan marketing campaigns, manage social media, analyze campaign performance, coordinate with clients.',
                'requirements' => 'Bachelor\'s degree in Marketing, 2+ years digital marketing experience, knowledge of SEO/SEM.',
                'min_experience_months' => 24,
                'salary_min' => 50000,
                'salary_max' => 80000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 0,
                'posting_date' => Carbon::now()->subDays(3),
                'last_apply_date' => Carbon::now()->addDays(25),
                'is_active' => 1
            ],
            [
                'company_id' => 3,
                'category_id' => 1,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 3,
                'job_type_id' => 1,
                'title' => 'Mobile App Developer',
                'slug' => 'mobile-app-developer',
                'description' => 'Develop mobile applications for iOS and Android platforms using Flutter framework.',
                'responsibilities' => 'Develop mobile apps, test applications, maintain code, collaborate with designers.',
                'requirements' => 'Bachelor\'s degree, Flutter experience, knowledge of mobile development.',
                'min_experience_months' => 24,
                'salary_min' => 70000,
                'salary_max' => 100000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(7),
                'last_apply_date' => Carbon::now()->addDays(20),
                'is_active' => 1
            ],
            [
                'company_id' => 4,
                'category_id' => 4,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 2,
                'job_type_id' => 2,
                'title' => 'Content Writer',
                'slug' => 'content-writer',
                'description' => 'Create engaging educational content for our online learning platform.',
                'responsibilities' => 'Write educational content, research topics, edit content, collaborate with subject matter experts.',
                'requirements' => 'Bachelor\'s degree in English/Journalism, excellent writing skills, 1+ year experience.',
                'min_experience_months' => 12,
                'salary_min' => 25000,
                'salary_max' => 40000,
                'currency' => 'PKR',
                'vacancies' => 2,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(2),
                'last_apply_date' => Carbon::now()->addDays(15),
                'is_active' => 1
            ],
            [
                'company_id' => 5,
                'category_id' => 3,
                'education_level_id' => 13,
                'country_id' => 1,
                'city_id' => 1,
                'job_type_id' => 1,
                'title' => 'Financial Analyst',
                'slug' => 'financial-analyst',
                'description' => 'Analyze financial data and prepare reports for investment decisions.',
                'responsibilities' => 'Analyze financial data, prepare reports, conduct research, provide recommendations.',
                'requirements' => 'Master\'s degree in Finance, CFA preferred, 2+ years experience.',
                'min_experience_months' => 24,
                'salary_min' => 90000,
                'salary_max' => 130000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 0,
                'posting_date' => Carbon::now()->subDays(1),
                'last_apply_date' => Carbon::now()->addDays(30),
                'is_active' => 1
            ],
            [
                'company_id' => 6,
                'category_id' => 2,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 3,
                'job_type_id' => 1,
                'title' => 'Healthcare IT Specialist',
                'slug' => 'healthcare-it-specialist',
                'description' => 'Manage healthcare information systems and ensure data security.',
                'responsibilities' => 'Manage IT systems, ensure data security, provide technical support, maintain records.',
                'requirements' => 'Bachelor\'s degree in IT/Healthcare, knowledge of healthcare systems, 2+ years experience.',
                'min_experience_months' => 24,
                'salary_min' => 60000,
                'salary_max' => 90000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 0,
                'posting_date' => Carbon::now()->subDays(4),
                'last_apply_date' => Carbon::now()->addDays(25),
                'is_active' => 1
            ],
            [
                'company_id' => 7,
                'category_id' => 8,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 4,
                'job_type_id' => 1,
                'title' => 'Renewable Energy Engineer',
                'slug' => 'renewable-energy-engineer',
                'description' => 'Design and implement renewable energy solutions for sustainable development.',
                'responsibilities' => 'Design energy systems, conduct feasibility studies, manage projects, ensure compliance.',
                'requirements' => 'Bachelor\'s degree in Engineering, renewable energy experience, project management skills.',
                'min_experience_months' => 36,
                'salary_min' => 75000,
                'salary_max' => 110000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 0,
                'posting_date' => Carbon::now()->subDays(6),
                'last_apply_date' => Carbon::now()->addDays(20),
                'is_active' => 1
            ],
            [
                'company_id' => 8,
                'category_id' => 1,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 1,
                'job_type_id' => 1,
                'title' => 'E-commerce Developer',
                'slug' => 'ecommerce-developer',
                'description' => 'Develop and maintain e-commerce platforms and online marketplaces.',
                'responsibilities' => 'Develop e-commerce features, integrate payment systems, optimize performance, maintain security.',
                'requirements' => 'Bachelor\'s degree in Computer Science, e-commerce experience, knowledge of payment gateways.',
                'min_experience_months' => 30,
                'salary_min' => 70000,
                'salary_max' => 100000,
                'currency' => 'PKR',
                'vacancies' => 2,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(8),
                'last_apply_date' => Carbon::now()->addDays(22),
                'is_active' => 1
            ],
            [
                'company_id' => 9,
                'category_id' => 30,
                'education_level_id' => 13,
                'country_id' => 1,
                'city_id' => 2,
                'job_type_id' => 1,
                'title' => 'Data Scientist',
                'slug' => 'data-scientist',
                'description' => 'Analyze complex data sets to help businesses make informed decisions.',
                'responsibilities' => 'Analyze data, build models, create visualizations, provide insights, collaborate with teams.',
                'requirements' => 'Master\'s degree in Data Science/Statistics, Python/R experience, machine learning knowledge.',
                'min_experience_months' => 24,
                'salary_min' => 85000,
                'salary_max' => 120000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(9),
                'last_apply_date' => Carbon::now()->addDays(21),
                'is_active' => 1
            ],
            [
                'company_id' => 10,
                'category_id' => 1,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 3,
                'job_type_id' => 1,
                'title' => 'Cloud Solutions Architect',
                'slug' => 'cloud-solutions-architect',
                'description' => 'Design and implement cloud-based solutions for modern businesses.',
                'responsibilities' => 'Design cloud architectures, implement solutions, ensure scalability, provide technical guidance.',
                'requirements' => 'Bachelor\'s degree in Computer Science, AWS/Azure certification, 3+ years cloud experience.',
                'min_experience_months' => 36,
                'salary_min' => 90000,
                'salary_max' => 130000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(10),
                'last_apply_date' => Carbon::now()->addDays(20),
                'is_active' => 1
            ],
            [
                'company_id' => 11,
                'category_id' => 1,
                'education_level_id' => 13,
                'country_id' => 1,
                'city_id' => 1,
                'job_type_id' => 1,
                'title' => 'AI/ML Engineer',
                'slug' => 'ai-ml-engineer',
                'description' => 'Develop artificial intelligence and machine learning solutions.',
                'responsibilities' => 'Develop AI models, implement ML algorithms, optimize performance, research new techniques.',
                'requirements' => 'Master\'s degree in AI/ML, Python/TensorFlow experience, 2+ years ML experience.',
                'min_experience_months' => 24,
                'salary_min' => 95000,
                'salary_max' => 140000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(11),
                'last_apply_date' => Carbon::now()->addDays(19),
                'is_active' => 1
            ],
            [
                'company_id' => 12,
                'category_id' => 1,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 2,
                'job_type_id' => 1,
                'title' => 'Blockchain Developer',
                'slug' => 'blockchain-developer',
                'description' => 'Develop blockchain applications and smart contracts.',
                'responsibilities' => 'Develop blockchain apps, write smart contracts, ensure security, maintain networks.',
                'requirements' => 'Bachelor\'s degree in Computer Science, blockchain experience, Solidity knowledge.',
                'min_experience_months' => 30,
                'salary_min' => 80000,
                'salary_max' => 120000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(12),
                'last_apply_date' => Carbon::now()->addDays(18),
                'is_active' => 1
            ],
            [
                'company_id' => 13,
                'category_id' => 25,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 3,
                'job_type_id' => 1,
                'title' => 'Cybersecurity Specialist',
                'slug' => 'cybersecurity-specialist',
                'description' => 'Protect businesses from cyber threats and ensure data security.',
                'responsibilities' => 'Monitor security systems, investigate threats, implement security measures, conduct audits.',
                'requirements' => 'Bachelor\'s degree in Cybersecurity, security certifications, 2+ years experience.',
                'min_experience_months' => 24,
                'salary_min' => 70000,
                'salary_max' => 100000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 0,
                'posting_date' => Carbon::now()->subDays(13),
                'last_apply_date' => Carbon::now()->addDays(17),
                'is_active' => 1
            ],
            [
                'company_id' => 14,
                'category_id' => 1,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 1,
                'job_type_id' => 1,
                'title' => 'Mobile App Designer',
                'slug' => 'mobile-app-designer',
                'description' => 'Design user interfaces for mobile applications.',
                'responsibilities' => 'Design mobile interfaces, create prototypes, collaborate with developers, conduct user testing.',
                'requirements' => 'Bachelor\'s degree in Design, mobile design experience, Figma/Sketch knowledge.',
                'min_experience_months' => 18,
                'salary_min' => 50000,
                'salary_max' => 75000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(14),
                'last_apply_date' => Carbon::now()->addDays(16),
                'is_active' => 1
            ],
            [
                'company_id' => 15,
                'category_id' => 1,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 2,
                'job_type_id' => 1,
                'title' => 'Full Stack Developer',
                'slug' => 'full-stack-developer',
                'description' => 'Develop both frontend and backend applications.',
                'responsibilities' => 'Develop web applications, maintain databases, implement APIs, ensure performance.',
                'requirements' => 'Bachelor\'s degree in Computer Science, full-stack experience, knowledge of multiple technologies.',
                'min_experience_months' => 30,
                'salary_min' => 75000,
                'salary_max' => 110000,
                'currency' => 'PKR',
                'vacancies' => 2,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(15),
                'last_apply_date' => Carbon::now()->addDays(15),
                'is_active' => 1
            ],
            [
                'company_id' => 16,
                'category_id' => 5,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 3,
                'job_type_id' => 1,
                'title' => 'Content Marketing Manager',
                'slug' => 'content-marketing-manager',
                'description' => 'Create and manage content marketing strategies.',
                'responsibilities' => 'Create content strategies, manage content calendar, analyze performance, coordinate with teams.',
                'requirements' => 'Bachelor\'s degree in Marketing, content marketing experience, SEO knowledge.',
                'min_experience_months' => 24,
                'salary_min' => 55000,
                'salary_max' => 80000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(16),
                'last_apply_date' => Carbon::now()->addDays(14),
                'is_active' => 1
            ],
            [
                'company_id' => 17,
                'category_id' => 5,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 1,
                'job_type_id' => 1,
                'title' => 'Social Media Manager',
                'slug' => 'social-media-manager',
                'description' => 'Manage social media presence and engagement for brands.',
                'responsibilities' => 'Manage social media accounts, create content, engage with audience, analyze metrics.',
                'requirements' => 'Bachelor\'s degree in Marketing, social media experience, content creation skills.',
                'min_experience_months' => 18,
                'salary_min' => 40000,
                'salary_max' => 60000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(17),
                'last_apply_date' => Carbon::now()->addDays(13),
                'is_active' => 1
            ],
            [
                'company_id' => 18,
                'category_id' => 5,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 2,
                'job_type_id' => 1,
                'title' => 'SEO Specialist',
                'slug' => 'seo-specialist',
                'description' => 'Optimize websites for search engines and improve rankings.',
                'responsibilities' => 'Optimize websites, conduct keyword research, analyze rankings, implement SEO strategies.',
                'requirements' => 'Bachelor\'s degree in Marketing, SEO experience, analytical skills.',
                'min_experience_months' => 24,
                'salary_min' => 45000,
                'salary_max' => 70000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(18),
                'last_apply_date' => Carbon::now()->addDays(12),
                'is_active' => 1
            ],
            [
                'company_id' => 19,
                'category_id' => 14,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 3,
                'job_type_id' => 1,
                'title' => 'Video Producer',
                'slug' => 'video-producer',
                'description' => 'Create engaging video content for marketing campaigns.',
                'responsibilities' => 'Plan video projects, coordinate production, edit videos, manage budgets.',
                'requirements' => 'Bachelor\'s degree in Media/Communications, video production experience, editing skills.',
                'min_experience_months' => 24,
                'salary_min' => 50000,
                'salary_max' => 75000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 0,
                'posting_date' => Carbon::now()->subDays(19),
                'last_apply_date' => Carbon::now()->addDays(11),
                'is_active' => 1
            ],
            [
                'company_id' => 20,
                'category_id' => 9,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 1,
                'job_type_id' => 1,
                'title' => 'Graphic Designer',
                'slug' => 'graphic-designer',
                'description' => 'Create visual designs for marketing materials and branding.',
                'responsibilities' => 'Create visual designs, develop brand identity, design marketing materials, collaborate with teams.',
                'requirements' => 'Bachelor\'s degree in Design, graphic design experience, Adobe Creative Suite knowledge.',
                'min_experience_months' => 18,
                'salary_min' => 40000,
                'salary_max' => 60000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(20),
                'last_apply_date' => Carbon::now()->addDays(10),
                'is_active' => 1
            ],
            [
                'company_id' => 21,
                'category_id' => 9,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 2,
                'job_type_id' => 1,
                'title' => 'UI/UX Designer',
                'slug' => 'ui-ux-designer',
                'description' => 'Design user interfaces and user experiences for digital products.',
                'responsibilities' => 'Design user interfaces, conduct user research, create prototypes, test usability.',
                'requirements' => 'Bachelor\'s degree in Design, UI/UX experience, prototyping tools knowledge.',
                'min_experience_months' => 24,
                'salary_min' => 55000,
                'salary_max' => 80000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(21),
                'last_apply_date' => Carbon::now()->addDays(9),
                'is_active' => 1
            ],
            [
                'company_id' => 22,
                'category_id' => 27,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 3,
                'job_type_id' => 1,
                'title' => 'QA Engineer',
                'slug' => 'qa-engineer',
                'description' => 'Ensure software quality through testing and quality assurance processes.',
                'responsibilities' => 'Test software applications, identify bugs, create test cases, ensure quality standards.',
                'requirements' => 'Bachelor\'s degree in Computer Science, QA experience, testing tools knowledge.',
                'min_experience_months' => 24,
                'salary_min' => 50000,
                'salary_max' => 75000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(22),
                'last_apply_date' => Carbon::now()->addDays(8),
                'is_active' => 1
            ],
            [
                'company_id' => 23,
                'category_id' => 28,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 1,
                'job_type_id' => 1,
                'title' => 'Project Manager',
                'slug' => 'project-manager',
                'description' => 'Manage software development projects and ensure timely delivery.',
                'responsibilities' => 'Plan projects, manage resources, track progress, communicate with stakeholders.',
                'requirements' => 'Bachelor\'s degree in Project Management, PMP certification preferred, 3+ years experience.',
                'min_experience_months' => 36,
                'salary_min' => 70000,
                'salary_max' => 100000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(23),
                'last_apply_date' => Carbon::now()->addDays(7),
                'is_active' => 1
            ],
            [
                'company_id' => 24,
                'category_id' => 30,
                'education_level_id' => 13,
                'country_id' => 1,
                'city_id' => 2,
                'job_type_id' => 1,
                'title' => 'Business Intelligence Analyst',
                'slug' => 'business-intelligence-analyst',
                'description' => 'Analyze business data to provide insights and recommendations.',
                'responsibilities' => 'Analyze business data, create reports, provide insights, support decision making.',
                'requirements' => 'Master\'s degree in Business Analytics, SQL experience, analytical skills.',
                'min_experience_months' => 24,
                'salary_min' => 65000,
                'salary_max' => 95000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(24),
                'last_apply_date' => Carbon::now()->addDays(6),
                'is_active' => 1
            ],
            [
                'company_id' => 25,
                'category_id' => 10,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 3,
                'job_type_id' => 1,
                'title' => 'Customer Success Manager',
                'slug' => 'customer-success-manager',
                'description' => 'Ensure customer satisfaction and success with our products.',
                'responsibilities' => 'Manage customer relationships, resolve issues, ensure satisfaction, drive retention.',
                'requirements' => 'Bachelor\'s degree in Business, customer service experience, communication skills.',
                'min_experience_months' => 24,
                'salary_min' => 45000,
                'salary_max' => 70000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(25),
                'last_apply_date' => Carbon::now()->addDays(5),
                'is_active' => 1
            ],
            [
                'company_id' => 26,
                'category_id' => 7,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 1,
                'job_type_id' => 1,
                'title' => 'HR Business Partner',
                'slug' => 'hr-business-partner',
                'description' => 'Partner with business units to provide HR support and solutions.',
                'responsibilities' => 'Provide HR support, manage employee relations, support recruitment, ensure compliance.',
                'requirements' => 'Bachelor\'s degree in HR, HR experience, business acumen.',
                'min_experience_months' => 30,
                'salary_min' => 60000,
                'salary_max' => 90000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 0,
                'posting_date' => Carbon::now()->subDays(26),
                'last_apply_date' => Carbon::now()->addDays(4),
                'is_active' => 1
            ],
            [
                'company_id' => 27,
                'category_id' => 13,
                'education_level_id' => 14,
                'country_id' => 1,
                'city_id' => 2,
                'job_type_id' => 1,
                'title' => 'Legal Counsel',
                'slug' => 'legal-counsel',
                'description' => 'Provide legal advice and support for technology companies.',
                'responsibilities' => 'Provide legal advice, review contracts, ensure compliance, handle legal matters.',
                'requirements' => 'LLB degree, legal experience, technology law knowledge.',
                'min_experience_months' => 36,
                'salary_min' => 80000,
                'salary_max' => 120000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 0,
                'posting_date' => Carbon::now()->subDays(27),
                'last_apply_date' => Carbon::now()->addDays(3),
                'is_active' => 1
            ],
            [
                'company_id' => 28,
                'category_id' => 21,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 3,
                'job_type_id' => 1,
                'title' => 'Real Estate Technology Specialist',
                'slug' => 'real-estate-technology-specialist',
                'description' => 'Develop technology solutions for real estate industry.',
                'responsibilities' => 'Develop real estate tech solutions, manage property systems, ensure efficiency.',
                'requirements' => 'Bachelor\'s degree in Real Estate/Technology, real estate experience, tech skills.',
                'min_experience_months' => 24,
                'salary_min' => 55000,
                'salary_max' => 80000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 1,
                'posting_date' => Carbon::now()->subDays(28),
                'last_apply_date' => Carbon::now()->addDays(2),
                'is_active' => 1
            ],
            [
                'company_id' => 29,
                'category_id' => 19,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 1,
                'job_type_id' => 1,
                'title' => 'Logistics Technology Manager',
                'slug' => 'logistics-technology-manager',
                'description' => 'Manage technology solutions for logistics and supply chain operations.',
                'responsibilities' => 'Manage logistics systems, optimize operations, ensure efficiency, coordinate with teams.',
                'requirements' => 'Bachelor\'s degree in Logistics/Technology, logistics experience, tech skills.',
                'min_experience_months' => 30,
                'salary_min' => 65000,
                'salary_max' => 95000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 0,
                'posting_date' => Carbon::now()->subDays(29),
                'last_apply_date' => Carbon::now()->addDays(1),
                'is_active' => 1
            ],
            [
                'company_id' => 30,
                'category_id' => 20,
                'education_level_id' => 12,
                'country_id' => 1,
                'city_id' => 2,
                'job_type_id' => 1,
                'title' => 'Agricultural Technology Specialist',
                'slug' => 'agricultural-technology-specialist',
                'description' => 'Develop technology solutions to improve agricultural practices.',
                'responsibilities' => 'Develop agri-tech solutions, improve farming practices, ensure sustainability.',
                'requirements' => 'Bachelor\'s degree in Agriculture/Technology, agricultural experience, tech skills.',
                'min_experience_months' => 24,
                'salary_min' => 50000,
                'salary_max' => 75000,
                'currency' => 'PKR',
                'vacancies' => 1,
                'is_remote' => 0,
                'posting_date' => Carbon::now()->subDays(30),
                'last_apply_date' => Carbon::now()->addDays(30),
                'is_active' => 1
            ]
        ];

        foreach ($jobs as $job) {
            Job::create($job);
        } */
    }
}